// CHRONO-Z BIG DATA – Dữ liệu đã được lưu bởi Web Builder

export const autoTimelineData = [
  {
    "id": 1,
    "period": "năm 2026",
    "source": "SGK Lịch sử 10 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "1000 năm thăng long ha hội",
    "basic": "",
    "advanced": "abc",
    "full_wiki": "abc",
    "wikiLinks": {},
    "imageUrl": "/images/1783574458213_grok_image_0c67acb2_f9e5_44cf_846d_d7826b6d743e.jpg"
  },
  {
    "id": 2,
    "period": "Năm 938",
    "source": "SGK Lịch sử 10 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Chiến thắng Bạch Đằng năm 938 – Ngô Quyền chấm dứt nghìn năm Bắc thuộc",
    "basic": "Năm 938, Ngô Quyền lãnh đạo quân dân Việt Nam đánh tan đoàn thuyền chiến Nam Hán trên sông Bạch Đằng. Ông sáng tạo chiến thuật đóng cọc gỗ bịt sắt nhọn dưới lòng sông, nhử địch vào khi thủy triều lên rồi phản công quyết liệt khi triều rút, tiêu diệt toàn bộ thủy quân địch, chủ tướng Hoằng Tháo tử trận. Chiến thắng này chấm dứt hơn 1.000 năm Bắc thuộc.",
    "advanced": "Chiến thắng Bạch Đằng năm 938 là một trong những trang sử hào hùng nhất của dân tộc. Nghệ thuật quân sự của Ngô Quyền thể hiện tư duy sáng tạo, tầm nhìn chiến lược: lợi dụng điều kiện tự nhiên (thủy triều, địa hình lòng sông hẹp), kết hợp giữa phòng thủ chiến lược và phản công chủ động, bất ngờ. Sau chiến thắng, Ngô Quyền xưng vương, đóng đô tại Cổ Loa, mở ra thời kỳ độc lập, tự chủ lâu dài cho dân tộc.",
    "full_wiki": "Bối cảnh lịch sử:\nSau khi nhà Đường sụp đổ (907), Trung Quốc bước vào thời kỳ Ngũ đại Thập quốc hỗn loạn. Tại Giao Châu, họ Khúc cai trị tự chủ. Năm 917, Nam Hán (một nước trong số các tiểu quốc thời Ngũ đại) xâm lược Giao Châu. Năm 931, Dương Đình Nghệ đuổi được quân Nam Hán, nhưng sau đó bị Kiều Công Tiễn (tướng phản bội) sát hại năm 937. Ngô Quyền – con rể của Dương Đình Nghệ – liền khởi binh đánh Kiều Công Tiễn, đồng thời chuẩn bị đối phó với quân Nam Hán.\n\nDiễn biến trận Bạch Đằng (cuối năm 938):\n1. Ngô Quyền cho quân đóng cọc gỗ bịt sắt nhọn ngầm dưới lòng sông Bạch Đằng, tính toán kỹ theo thủy triều.\n2. Khi thủy triều lên cao, thuyền nhỏ của ta nhử đoàn thuyền lớn của Nam Hán (do Hoằng Tháo chỉ huy) tiến sâu vào cửa sông.\n3. Thủy triều rút, thuyền Nam Hán mắc vào cọc, không thể cơ động được.\n4. Quân ta từ hai bờ và phía sau đồng loạt tấn công. Hoằng Tháo tử trận, toàn bộ thủy quân Nam Hán bị tiêu diệt.\n5. Vua Nam Hán (Lưu Cung) kinh hoàng, bãi bỏ ý định tiếp tục xâm lược.\n\nKết quả và ý nghĩa:\n• Chấm dứt vĩnh viễn ách đô hộ của phong kiến phương Bắc kéo dài hơn 1.000 năm.\n• Ngô Quyền xưng vương (Ngô Vương), xây dựng chính quyền độc lập tại Cổ Loa.\n• Mở ra thời kỳ độc lập, tự chủ lâu dài của các triều đại Đinh – Tiền Lê – Lý – Trần – Hậu Lê.\n• Trận Bạch Đằng trở thành biểu tượng về tư duy quân sự sáng tạo, khai thác tối đa điều kiện tự nhiên để đánh bại kẻ thù mạnh hơn.",
    "wikiLinks": {}
  },
  {
    "id": 3,
    "period": "Năm 1010 – Năm 1225",
    "source": "SGK Lịch sử 10 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Nhà Lý – Xây dựng nhà nước phong kiến độc lập vững mạnh",
    "basic": "Năm 1009, Lý Công Uẩn lên ngôi, lập nhà Lý. Năm 1010, ông ban \"Chiếu dời đô\", chuyển kinh đô từ Hoa Lư về Thăng Long (Hà Nội ngày nay). Nhà Lý (1009–1225) là triều đại đầu tiên xây dựng nhà nước phong kiến Việt Nam trên quy mô lớn, với Thăng Long là trung tâm chính trị, kinh tế và văn hóa trong nhiều thế kỷ.",
    "advanced": "Nhà Lý đạt được nhiều thành tựu nổi bật: Ban hành Hình thư – bộ luật thành văn đầu tiên (1042); xây dựng Văn Miếu – Quốc Tử Giám (1070–1076) – trường đại học đầu tiên; tổ chức khoa thi đầu tiên (1075). Đặc biệt, năm 1075–1077, Lý Thường Kiệt chỉ huy đánh bại quân Tống bảo vệ nền độc lập. Bài thơ \"Nam quốc sơn hà\" của Lý Thường Kiệt được coi là bản Tuyên ngôn độc lập đầu tiên của Việt Nam.",
    "full_wiki": "Nhà Lý (1009–1225) – 9 đời vua, 216 năm trị vì. Những thành tựu chủ yếu:\n\n1. Chính trị và hành chính:\n• 1010: \"Chiếu dời đô\" – quyết định mang tầm nhìn chiến lược, đặt nền móng cho Thăng Long ngàn năm văn hiến.\n• Xây dựng bộ máy nhà nước trung ương tập quyền, chia cả nước thành 24 lộ.\n• 1042: Ban hành bộ Hình thư – bộ luật thành văn đầu tiên của Việt Nam.\n\n2. Giáo dục và văn hóa:\n• 1070: Xây dựng Văn Miếu tại Thăng Long để thờ Khổng Tử và dạy học.\n• 1076: Thành lập Quốc Tử Giám – trường đại học đầu tiên của Việt Nam, dành cho con em quý tộc và quan lại.\n• 1075: Tổ chức khoa thi Minh kinh bác học – lần đầu tiên tuyển chọn nhân tài qua thi cử.\n\n3. Quân sự và đối ngoại:\n• Chiến tranh Lý – Tống (1075–1077):\n   - Năm 1075: Lý Thường Kiệt chủ động \"tiên phát chế nhân\" – tấn công phủ đầu vào các căn cứ của Tống ở Ung Châu, Khâm Châu, Liêm Châu để phá vỡ kế hoạch xâm lược của địch.\n   - Năm 1077: Phòng thủ trên phòng tuyến sông Cầu (sông Như Nguyệt). Lý Thường Kiệt sáng tác bài thơ \"Nam quốc sơn hà\" cổ vũ tinh thần quân sĩ và khẳng định chủ quyền lãnh thổ.\n   - Kết quả: Quân Tống bị đánh bại, phải rút về nước.\n\n4. Kinh tế và xã hội:\n• Phát triển nông nghiệp: đắp đê ngăn lũ, đào kênh tưới tiêu, thực hiện \"ruộng quân điền\".\n• Chính sách \"Ngụ binh ư nông\": Lính đồng thời là nông dân, vừa sản xuất vừa sẵn sàng chiến đấu – tiết kiệm ngân sách quốc gia.\n• Phát triển thủ công nghiệp: gốm sứ Lý (men ngọc xanh), đồ đồng, dệt lụa.\n\nDi sản:\nNhà Lý để lại nền móng vững chắc cho một quốc gia phong kiến độc lập có nền văn hóa phát triển cao. Thăng Long trở thành trung tâm chính trị – kinh tế – văn hóa suốt nhiều thế kỷ sau.",
    "wikiLinks": {}
  },
  {
    "id": 4,
    "period": "Năm 1226 – Năm 1400",
    "source": "SGK Lịch sử 10 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Nhà Trần – Ba lần đại thắng quân Mông – Nguyên",
    "basic": "Nhà Trần (1226–1400) lập nên kỳ tích ba lần đánh thắng quân Mông – Nguyên (1258, 1285, 1287–1288) – đế quốc hùng mạnh nhất thế giới thời bấy giờ, đã chinh phục từ Châu Á đến Đông Âu. Chiến lược \"vườn không nhà trống\", tiêu hao sinh lực địch rồi phản công quyết liệt là bài học quân sự vô giá.",
    "advanced": "Ba lần kháng chiến chống Mông – Nguyên là minh chứng sáng ngời cho đường lối chiến tranh toàn dân. Hội nghị Diên Hồng (1285): Vua Trần hỏi toàn thể bô lão \"Nên đánh hay nên hòa?\", toàn bộ đồng thanh đáp \"Quyết đánh!\". Hưng Đạo Vương Trần Quốc Tuấn soạn \"Hịch tướng sĩ\" và \"Binh thư yếu lược\" – những áng hùng văn và tác phẩm quân sự vô giá của dân tộc.",
    "full_wiki": "Nhà Trần (1226–1400) – 13 đời vua, 175 năm trị vì.\n\nKháng chiến chống Mông – Nguyên lần 1 (1258):\n• Tháng 1/1258: Quân Mông Cổ do Uriyangkhadai chỉ huy tiến vào Thăng Long.\n• Vua Trần Thái Tông thực hiện chiến thuật \"vườn không nhà trống\": sơ tán dân, di chuyển tài sản, không để địch cướp phá.\n• Quân ta phản công mạnh mẽ tại Đông Bộ Đầu. Quân Mông Cổ thiếu lương thực, bệnh dịch hoành hành, buộc phải rút lui.\n\nKháng chiến chống Mông – Nguyên lần 2 (1285):\n• Khoảng 50 vạn quân Nguyên do Thoát Hoan chỉ huy từ phía Bắc, kết hợp Toa Đô từ phía Nam tạo thế gọng kìm.\n• Hội nghị Diên Hồng: Toàn dân quyết tâm kháng chiến.\n• Trần Quốc Tuấn soạn \"Hịch tướng sĩ\" cổ vũ quân sĩ lòng yêu nước và ý chí chiến đấu.\n• Phản công: Ta lần lượt giành thắng lợi tại Tây Kết, Hàm Tử, Chương Dương, rồi giải phóng Thăng Long.\n• Toa Đô bị giết, Thoát Hoan phải chui vào ống đồng chạy về nước.\n\nKháng chiến chống Mông – Nguyên lần 3 (1287–1288):\n• Nguyên Thế Tổ sai Thoát Hoan dẫn đại quân xâm lược lần thứ ba.\n• Trận Vân Đồn (cuối 1287): Trần Khánh Dư đánh chặn và tiêu diệt đoàn thuyền lương của Trương Văn Hổ – chặt đứt hậu cần của địch.\n• Trận Bạch Đằng (tháng 4/1288): Trần Quốc Tuấn tái sử dụng chiến thuật cọc gỗ của Ngô Quyền. Toàn bộ đoàn thuyền của Ô Mã Nhi bị tiêu diệt. Ô Mã Nhi bị bắt sống.\n\nBài học lịch sử:\n• Đoàn kết toàn dân là nguồn sức mạnh vô địch.\n• Chiến thuật linh hoạt: Rút lui bảo toàn lực lượng khi địch mạnh, phản công quyết liệt khi địch suy yếu.\n• Kết hợp chiến tranh du kích, tiêu hao với tiêu diệt sinh lực địch quy mô lớn trong trận quyết chiến chiến lược.",
    "wikiLinks": {}
  },
  {
    "id": 5,
    "period": "Năm 1418 – Năm 1527",
    "source": "SGK Lịch sử 11 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Khởi nghĩa Lam Sơn và Nhà Lê Sơ – Đỉnh cao nhà nước phong kiến Việt Nam",
    "basic": "Năm 1418, Lê Lợi dựng cờ khởi nghĩa tại Lam Sơn (Thanh Hóa). Sau 10 năm kháng chiến gian khổ (1418–1428), nghĩa quân Lam Sơn đánh đuổi quân Minh xâm lược, giải phóng đất nước. Lê Lợi lên ngôi hoàng đế, lập nhà Lê Sơ. Nguyễn Trãi soạn \"Bình Ngô đại cáo\" (1428) – bản Tuyên ngôn độc lập thứ hai của dân tộc Việt Nam.",
    "advanced": "Dưới thời Lê Thánh Tông (1460–1497), đất nước phát triển hưng thịnh nhất lịch sử phong kiến: cải cách hành chính toàn diện, ban hành Bộ luật Hồng Đức (1483) – bộ luật tiến bộ nhất phong kiến Việt Nam (bảo vệ quyền phụ nữ, nghiêm trị tham nhũng). Thành lập Hội Tao Đàn, phát triển văn học chữ Nôm. Năm 1471, thực hiện chiến dịch bình Chiêm, mở rộng lãnh thổ đến Bình Định.",
    "full_wiki": "Khởi nghĩa Lam Sơn (1418–1428):\n\nBối cảnh: Nhà Minh xâm lược Việt Nam (1407), lập ra chế độ đô hộ tàn bạo: đốt sách, bắt người đi lao dịch, vơ vét tài nguyên, áp đặt văn hóa Hán.\n\nNgười lãnh đạo: Lê Lợi (1385–1433) – người hào trưởng giàu có ở Lam Sơn, có lòng yêu nước sâu sắc, từ chối nhiều lần mời mọc của quân Minh.\n\nCố vấn chiến lược: Nguyễn Trãi – đại trí thức, soạn thảo chiến lược toàn diện, trong đó có \"Bình Ngô sách\" nêu rõ đường lối đánh giặc.\n\nDiễn biến:\n• Giai đoạn khó khăn (1418–1423): Căn cứ Lam Sơn nhiều lần bị vây hãm. Nghĩa quân phải di chuyển, vừa đánh vừa lui.\n• Giai đoạn phát triển (1424–1426): Mở mặt trận Nghệ An – Thanh Hóa, xây dựng vùng giải phóng rộng lớn.\n• Giai đoạn quyết định (1426–1428): Bắc tiến, đánh bại các đạo viện binh Minh. Thành Đông Quan (Hà Nội) bị vây hãm. Quân Minh xin giảng hòa, rút về nước.\n\nNhà Lê Sơ (1428–1527) – thành tựu chủ yếu:\n\n1. Chính trị:\n• Tổ chức bộ máy nhà nước hoàn chỉnh: 6 bộ (Lại, Hộ, Lễ, Binh, Hình, Công).\n• Lê Thánh Tông chia cả nước thành 13 đạo thừa tuyên, xóa bỏ các chức tể tướng và phiên vương.\n\n2. Pháp luật:\n• 1483: Ban hành Bộ luật Hồng Đức (Quốc triều hình luật) – thành tựu pháp lý xuất sắc nhất thời phong kiến.\n• Tiến bộ vượt thời đại: Quy định quyền phụ nữ được ly hôn khi bị bạo hành, quyền thừa kế tài sản; xử phạt nặng quan lại tham nhũng.\n\n3. Giáo dục và văn hóa:\n• Phát triển khoa cử: định kỳ 3 năm thi Hội, thi Đình. Dựng bia Tiến sĩ tại Văn Miếu từ năm 1484.\n• Thành lập Hội Tao Đàn (1495), phát triển thơ văn chữ Nôm.\n\n4. Kinh tế:\n• Thực hiện phép quân điền: chia đều ruộng đất theo định kỳ 6 năm.\n• Khuyến khích khai hoang, phát triển nghề thủ công và buôn bán.\n\n5. Đối ngoại:\n• 1471: Lê Thánh Tông thân chinh đánh Chiêm Thành, mở mang bờ cõi đến Bình Định.\n• 1490: Hoàn thành Bản đồ Hồng Đức – tác phẩm địa lý học xuất sắc đầu tiên của Việt Nam.",
    "wikiLinks": {}
  },
  {
    "id": 6,
    "period": "Năm 1858 – Năm 1884",
    "source": "SGK Lịch sử 11 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Thực dân Pháp xâm lược Việt Nam – Nhà Nguyễn từng bước đầu hàng",
    "basic": "Ngày 1/9/1858, liên quân Pháp – Tây Ban Nha nổ súng tấn công bán đảo Sơn Trà (Đà Nẵng), mở đầu cuộc xâm lược Việt Nam. Triều đình nhà Nguyễn từng bước nhượng bộ qua các hòa ước: Nhâm Tuất (5/6/1862) nhường 3 tỉnh miền Đông Nam Kỳ; Giáp Tuất (1874) thừa nhận chủ quyền của Pháp với toàn bộ Nam Kỳ; Quý Mùi (25/8/1883) và Giáp Thân (6/6/1884) xác lập quyền bảo hộ của Pháp trên toàn Việt Nam.",
    "advanced": "Sự thất bại của triều đình nhà Nguyễn có nhiều nguyên nhân: chính sách \"bế quan tỏa cảng\" lạc hậu, không tiếp thu khoa học kỹ thuật phương Tây; kinh tế nông nghiệp lạc hậu; quân sự yếu kém; không có đường lối kháng chiến nhất quán, thậm chí phân tâm giữa \"chủ chiến\" và \"chủ hòa\". Sự hèn nhát của triều đình tương phản rõ nét với tinh thần chiến đấu kiên cường của nhân dân qua các phong trào: Trương Định, Nguyễn Trung Trực, Phong trào Cần Vương.",
    "full_wiki": "Nguyên nhân Pháp xâm lược Việt Nam:\n• Kinh tế: Tư bản Pháp cần thị trường tiêu thụ hàng hóa và nguồn nguyên liệu cho công nghiệp phát triển sau Cách mạng Công nghiệp.\n• Địa chiến lược: Việt Nam là cửa ngõ tiến vào vùng Nam Á và Trung Quốc rộng lớn.\n• Tôn giáo: Lấy cớ bảo vệ các giáo sĩ và tín đồ Thiên Chúa giáo bị triều đình cấm đạo.\n• Thuộc địa: Nằm trong chiến lược thuộc địa hóa toàn cầu của các cường quốc châu Âu thế kỷ XIX.\n\nQuá trình xâm lược:\n• 1/9/1858: Tấn công Đà Nẵng. Quân dân ta kháng cự mạnh, Pháp bị cầm chân hơn 5 tháng.\n• 2/1859: Pháp chuyển hướng vào Gia Định.\n• 5/6/1862: Hòa ước Nhâm Tuất – triều đình nhường 3 tỉnh miền Đông Nam Kỳ (Gia Định, Định Tường, Biên Hòa).\n• 1867: Pháp chiếm nốt 3 tỉnh miền Tây Nam Kỳ.\n• 1882–1883: Pháp tấn công ra Bắc Kỳ, đánh chiếm Hà Nội lần thứ hai. Tổng đốc Hoàng Diệu tuẫn tiết.\n• 25/8/1883: Hòa ước Quý Mùi (Harmand) – triều đình chấp nhận quyền bảo hộ của Pháp.\n• 6/6/1884: Hòa ước Giáp Thân (Patenôtre) – Việt Nam chính thức mất độc lập.\n\nPhong trào kháng chiến của nhân dân:\n• Trương Định: Không tuân lệnh triều đình giải tán nghĩa binh, tiếp tục kháng chiến ở Gò Công cho đến khi hy sinh (1864). Câu nói \"Trận này tớ thề quyết tử cho quê hương\".\n• Nguyễn Trung Trực: Đốt cháy tàu chiến Espérance của Pháp trên sông Vàm Cỏ Đông (1861). Bị bắt và bị xử tử (1868) với câu nói khí khái: \"Bao giờ người Tây nhổ hết cỏ nước Nam thì mới hết người Nam đánh Tây\".\n• Phong trào Cần Vương (1885–1896): Vua Hàm Nghi ban chiếu Cần Vương, kêu gọi văn thân, sĩ phu và nhân dân đứng lên giúp vua chống Pháp. Nhiều cuộc khởi nghĩa nổ ra: Bãi Sậy, Hương Khê, Ba Đình.",
    "wikiLinks": {}
  },
  {
    "id": 7,
    "period": "Năm 1919 – Năm 1930",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Phong trào yêu nước và sự ra đời của Đảng Cộng sản Việt Nam (3/2/1930)",
    "basic": "Sau Chiến tranh thế giới thứ nhất, phong trào yêu nước Việt Nam phát triển mạnh mẽ với hai khuynh hướng chủ yếu: tư sản (Phan Bội Châu chủ trương bạo động; Phan Châu Trinh chủ trương cải cách) và vô sản (Nguyễn Ái Quốc theo chủ nghĩa Mác – Lênin). Ngày 3/2/1930, Đảng Cộng sản Việt Nam được thành lập tại Hương Cảng (Hồng Kông) dưới sự chủ trì của Nguyễn Ái Quốc, đánh dấu bước ngoặt vĩ đại trong lịch sử cách mạng Việt Nam.",
    "advanced": "Sự ra đời của Đảng Cộng sản Việt Nam chấm dứt tình trạng khủng hoảng về đường lối và giai cấp lãnh đạo cách mạng. Cương lĩnh chính trị đầu tiên do Nguyễn Ái Quốc soạn thảo xác định: Làm cách mạng tư sản dân quyền và thổ địa cách mạng để đi tới xã hội cộng sản. Lực lượng cách mạng là giai cấp công nhân, nông dân liên minh với các tầng lớp tiểu tư sản và dân tộc tư sản. Đây là sự vận dụng sáng tạo chủ nghĩa Mác – Lênin vào điều kiện cụ thể của Việt Nam.",
    "full_wiki": "Bối cảnh lịch sử (1919–1930):\nSau Chiến tranh thế giới thứ nhất, thực dân Pháp tăng cường khai thác thuộc địa Việt Nam. Giai cấp công nhân và nông dân ngày càng bần cùng hóa. Mâu thuẫn xã hội gay gắt.\n\nHành trình tìm đường cứu nước của Nguyễn Ái Quốc:\n• 5/6/1911: Nguyễn Tất Thành (Hồ Chí Minh) rời Sài Gòn trên tàu Amiral Latouche Tréville đi tìm đường cứu nước.\n• 1919: Gửi Bản yêu sách 8 điểm đến Hội nghị Versailles (đòi các quyền tự do, dân chủ cho nhân dân An Nam) – không được chấp nhận nhưng gây tiếng vang lớn.\n• 12/1920: Đọc \"Sơ thảo lần thứ nhất những luận cương về vấn đề dân tộc và thuộc địa\" của Lenin. Nhận ra: chỉ có cách mạng vô sản mới giải phóng được dân tộc thuộc địa → Bỏ phiếu tán thành Đệ Tam Quốc tế, gia nhập Đảng Cộng sản Pháp.\n• 1924: Sang Quảng Châu (Trung Quốc), thành lập Hội Việt Nam Cách mạng Thanh niên (6/1925), đào tạo cán bộ cách mạng.\n• 1927: Xuất bản \"Đường Kách mệnh\" – tác phẩm lý luận nền tảng của cách mạng Việt Nam.\n\nSự ra đời của Đảng Cộng sản Việt Nam (3/2/1930):\n• Bối cảnh: Ba tổ chức cộng sản ra đời năm 1929 (Đông Dương Cộng sản Đảng, An Nam Cộng sản Đảng, Đông Dương Cộng sản Liên đoàn) hoạt động riêng lẻ, không thống nhất.\n• 3/2/1930: Nguyễn Ái Quốc triệu tập Hội nghị hợp nhất tại Cửu Long (Hương Cảng), hợp nhất ba tổ chức thành Đảng Cộng sản Việt Nam.\n• Thông qua: Chánh cương vắn tắt, Sách lược vắn tắt, Điều lệ vắn tắt.\n\nÝ nghĩa:\n• Chấm dứt khủng hoảng về đường lối và giai cấp lãnh đạo cách mạng.\n• Cách mạng Việt Nam từ đây có người lãnh đạo duy nhất, đường lối đúng đắn và tổ chức chặt chẽ.\n• Là bước ngoặt vĩ đại trong lịch sử dân tộc, gắn cách mạng Việt Nam với phong trào cách mạng thế giới.",
    "wikiLinks": {}
  },
  {
    "id": 8,
    "period": "Năm 1930 – Năm 1931",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Phong trào cách mạng 1930–1931 và Xô viết Nghệ – Tĩnh",
    "basic": "Năm 1930–1931, dưới sự lãnh đạo của Đảng Cộng sản Việt Nam, phong trào đấu tranh của công nhân và nông dân bùng nổ rầm rộ trong cả nước. Đỉnh cao là phong trào Xô viết Nghệ – Tĩnh (tại Nghệ An và Hà Tĩnh), nơi lần đầu tiên trong lịch sử Việt Nam, chính quyền công – nông xuất hiện và hoạt động ở một số xã, huyện.",
    "advanced": "Tuy phong trào 1930–1931 bị thực dân Pháp đàn áp đẫm máu và cuối cùng thất bại, nhưng đây được xem là \"cuộc diễn tập đầu tiên\" của Đảng và quần chúng chuẩn bị cho cách mạng thắng lợi. Phong trào đã khẳng định sức mạnh chiến đấu của nhân dân dưới ngọn cờ của Đảng, để lại những bài học kinh nghiệm quý báu về xây dựng lực lượng và tổ chức quần chúng.",
    "full_wiki": "Bối cảnh:\n• 1929–1933: Cuộc khủng hoảng kinh tế thế giới (\"Đại suy thoái\") tác động mạnh đến Đông Dương.\n• Pháp tăng cường bóc lột: cắt giảm lương công nhân, nâng thuế, thu hẹp sản xuất → hàng loạt công nhân thất nghiệp, nông dân bần cùng.\n\nDiễn biến:\n• Trong nước: Ngay sau khi Đảng ra đời, các chi bộ tổ chức biểu tình, bãi công ở khắp nơi.\n• Trung tâm phong trào: Nghệ An và Hà Tĩnh – nơi có truyền thống đấu tranh lâu đời.\n• Tháng 9/1930: Phong trào lên đến đỉnh điểm. Hàng ngàn nông dân biểu tình có vũ trang tại Hưng Nguyên (Nghệ An).\n• Thực dân Pháp cho máy bay ném bom vào đoàn biểu tình → hàng trăm người chết và bị thương.\n\nXô viết Nghệ – Tĩnh:\n• Tại một số huyện ở Nghệ An và Hà Tĩnh, bộ máy chính quyền thực dân và phong kiến tan rã.\n• Các chi bộ Đảng lãnh đạo nông dân tự đứng ra quản lý xã hội theo kiểu \"Xô viết\" (hội đồng đại biểu nhân dân).\n• Chính sách mới: Chia ruộng đất cho dân cày, bãi bỏ thuế thân, tổ chức đời sống văn minh, dạy chữ quốc ngữ.\n• Kéo dài đến đầu năm 1931 thì bị đàn áp.\n\nÝ nghĩa:\n• Lần đầu tiên chính quyền công – nông xuất hiện ở Việt Nam, dù chỉ tồn tại ngắn ngủi.\n• Để lại bài học: Phải xây dựng lực lượng cách mạng đủ mạnh, tổ chức chặt chẽ và chờ thời cơ chín muồi mới khởi nghĩa.",
    "wikiLinks": {}
  },
  {
    "id": 9,
    "period": "Năm 1939 – Năm 1945",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Cách mạng tháng Tám năm 1945 – Nước Việt Nam Dân chủ Cộng hòa ra đời",
    "basic": "Cách mạng tháng Tám 1945 là một cuộc cách mạng vĩ đại, mang tính toàn dân sâu sắc. Trong vòng chưa đầy 2 tuần (14–28/8/1945), nhân dân Việt Nam dưới sự lãnh đạo của Đảng và Mặt trận Việt Minh đã đồng loạt nổi dậy giành chính quyền trong cả nước. Ngày 2/9/1945, tại Quảng trường Ba Đình, Hà Nội, Chủ tịch Hồ Chí Minh đọc Tuyên ngôn Độc lập, khai sinh nước Việt Nam Dân chủ Cộng hòa.",
    "advanced": "Thành công của Cách mạng tháng Tám xuất phát từ ba nhân tố: (1) Đường lối cách mạng đúng đắn của Đảng và Bác Hồ, được chuẩn bị qua nhiều năm; (2) Lực lượng cách mạng (Mặt trận Việt Minh, lực lượng vũ trang) được xây dựng vững chắc; (3) Thời cơ cách mạng xuất hiện đúng lúc: Nhật đầu hàng Đồng minh ngày 15/8/1945, chính quyền bù nhìn tê liệt, chưa có quân Đồng minh vào. Đây là thời điểm \"ngàn năm có một\" – Đảng và Bác Hồ đã nắm bắt chính xác và quyết đoán.",
    "full_wiki": "Bối cảnh lịch sử:\n• Chiến tranh thế giới thứ hai bước vào giai đoạn kết thúc.\n• 9/3/1945: Nhật đảo chính Pháp, độc chiếm Đông Dương. Đảng ta ra bản \"Nhật – Pháp bắn nhau và hành động của chúng ta\".\n• Phong trào kháng Nhật cứu nước dâng cao (3–8/1945).\n• 7/5/1945: Đức phát xít đầu hàng. Chiến trường Thái Bình Dương chuyển biến nhanh.\n• 6/8 và 9/8/1945: Mỹ ném bom nguyên tử xuống Hiroshima và Nagasaki.\n• 15/8/1945: Nhật tuyên bố đầu hàng vô điều kiện – thời cơ \"ngàn năm có một\" xuất hiện.\n\nChuẩn bị cách mạng của Đảng:\n• 1941: Hội nghị Trung ương lần thứ 8 tại Pác Bó (Cao Bằng). Hồ Chí Minh về nước trực tiếp lãnh đạo. Mặt trận Việt Minh ra đời.\n• Xây dựng căn cứ địa Việt Bắc, lực lượng vũ trang: Cứu quốc quân (1941), Việt Nam tuyên truyền giải phóng quân (22/12/1944).\n• Cao trào kháng Nhật (3–8/1945): Thành lập Ủy ban Dân tộc giải phóng Việt Nam tại Tân Trào.\n\nDiễn biến Tổng khởi nghĩa:\n• 13/8/1945: Ủy ban Khởi nghĩa toàn quốc ban bố lệnh Tổng khởi nghĩa.\n• 16/8/1945: Đại hội Quốc dân Tân Trào thông qua quyết định Tổng khởi nghĩa.\n• 19/8/1945: Hà Nội giành chính quyền trong không khí náo nhiệt của hàng chục vạn người.\n• 23/8/1945: Huế giành chính quyền. Vua Bảo Đại tuyên bố thoái vị (25/8).\n• 25/8/1945: Sài Gòn giành chính quyền.\n• 2/9/1945: Tại Quảng trường Ba Đình, Chủ tịch Hồ Chí Minh đọc Tuyên ngôn Độc lập, khai sinh nước Việt Nam Dân chủ Cộng hòa.\n\nÝ nghĩa lịch sử:\n• Chấm dứt hơn 80 năm thực dân Pháp thống trị và gần 5 năm ách quân phiệt Nhật.\n• Lật đổ chế độ quân chủ phong kiến tồn tại hàng nghìn năm.\n• Khai sinh nhà nước Việt Nam Dân chủ Cộng hòa – nhà nước dân chủ nhân dân đầu tiên ở Đông Nam Á.\n• Mở ra kỷ nguyên mới: Độc lập dân tộc gắn liền với chủ nghĩa xã hội.\n• Cổ vũ mạnh mẽ phong trào giải phóng dân tộc trên toàn thế giới.",
    "wikiLinks": {}
  },
  {
    "id": 10,
    "period": "Năm 1946 – Năm 1954",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Kháng chiến chống Pháp – Chiến thắng Điện Biên Phủ (7/5/1954)",
    "basic": "Ngày 19/12/1946, Chủ tịch Hồ Chí Minh ra \"Lời kêu gọi toàn quốc kháng chiến\", mở đầu cuộc kháng chiến 9 năm chống thực dân Pháp. Đường lối kháng chiến: Toàn dân, toàn diện, trường kỳ, dựa vào sức mình là chính. Chiến dịch Điện Biên Phủ (13/3–7/5/1954), dưới sự chỉ huy của Đại tướng Võ Nguyên Giáp, đã đập tan tập đoàn cứ điểm Điện Biên Phủ, chấm dứt chiến tranh.",
    "advanced": "Chiến thắng Điện Biên Phủ là đỉnh cao của cuộc kháng chiến, mang ý nghĩa toàn cầu. Đại tướng Võ Nguyên Giáp đã thay đổi chiến thuật quan trọng: từ \"đánh nhanh thắng nhanh\" sang \"đánh chắc tiến chắc\", kéo pháo vào rồi kéo pháo ra để bố trí lại, chờ thời cơ chín muồi. Đây là quyết định sáng suốt và dũng cảm, thể hiện nghệ thuật quân sự thiên tài. Hiệp định Giơnevơ (21/7/1954) được ký kết, công nhận độc lập của Việt Nam.",
    "full_wiki": "Giai đoạn đầu kháng chiến (1946–1950):\n• 19/12/1946: Toàn quốc kháng chiến. Nhân dân Hà Nội chiến đấu giam chân địch 60 ngày.\n• 1947: Chiến dịch Việt Bắc Thu – Đông. Pháp tấn công căn cứ Việt Bắc nhưng thất bại.\n• 1950: Chiến dịch Biên giới Thu – Đông. Quân ta chủ động tấn công, giải phóng tuyến biên giới Việt – Trung, khai thông liên lạc quốc tế.\n\nGiai đoạn phát triển (1951–1953):\n• Đại hội Đảng lần thứ II (2/1951): Đảng ra hoạt động công khai, thông qua chính cương.\n• Nhiều chiến dịch tiêu hao sinh lực địch trên nhiều mặt trận.\n• Địch điều chỉnh chiến lược với \"Kế hoạch Navarre\" (11/1953): Tập trung 44 tiểu đoàn cơ động tinh nhuệ.\n\nChiến dịch Điện Biên Phủ (13/3–7/5/1954):\n• Pháp xây dựng tập đoàn cứ điểm Điện Biên Phủ (49 cứ điểm, 16.000 quân) – được mệnh danh là \"pháo đài bất khả xâm phạm\", \"Verdun của Đông Dương\".\n• Bộ Chỉ huy ta quyết định \"đánh chắc tiến chắc\": kéo pháo nặng vào trận địa (200 khẩu pháo được đưa qua núi cao, rừng sâu bằng sức người).\n• 13/3/1954: Mở màn chiến dịch, tấn công vào Him Lam, Độc Lập, Bản Kéo (đợt 1).\n• Đợt 2 (30/3–26/4): Tấn công dồn dập vào các cứ điểm vòng ngoài, thắt chặt vòng vây.\n• Đợt 3 (1–7/5): Tổng công kích. Tướng De Castries ra hàng lúc 17 giờ 30 phút ngày 7/5/1954.\n\nHiệp định Giơnevơ (21/7/1954):\n• Pháp thừa nhận độc lập, chủ quyền, thống nhất và toàn vẹn lãnh thổ của Việt Nam, Lào, Campuchia.\n• Tạm thời chia đôi Việt Nam tại vĩ tuyến 17. Tổng tuyển cử thống nhất vào 7/1956 (không được thực hiện).\n• Pháp phải rút quân trong 300 ngày.\n\nÝ nghĩa:\n• Chiến thắng Điện Biên Phủ \"lừng lẫy năm châu, chấn động địa cầu\".\n• Đặt dấu chấm hết cho chủ nghĩa thực dân kiểu cũ.\n• Cổ vũ mạnh mẽ phong trào giải phóng dân tộc, đặc biệt tại châu Phi.",
    "wikiLinks": {}
  },
  {
    "id": 11,
    "period": "Năm 1954 – Năm 1975",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Kháng chiến chống Mỹ – Đại thắng mùa Xuân 1975, thống nhất đất nước",
    "basic": "Sau Hiệp định Giơnevơ, Mỹ thay Pháp dựng chính quyền tay sai, phá hoại việc thống nhất đất nước. Nhân dân Việt Nam tiến hành cuộc kháng chiến chống Mỹ cứu nước (1954–1975). Đỉnh cao là Chiến dịch Hồ Chí Minh (26/4–30/4/1975), giải phóng Sài Gòn. Lúc 11 giờ 30 phút ngày 30/4/1975, lá cờ giải phóng tung bay trên Dinh Độc Lập, kết thúc 21 năm kháng chiến, thống nhất đất nước sau hơn 20 năm chia cắt.",
    "advanced": "Cuộc kháng chiến chống Mỹ là cuộc chiến tranh nhân dân vĩ đại nhất trong lịch sử. Mỹ đã sử dụng lực lượng quân sự khổng lồ (hơn 500.000 quân Mỹ năm 1969, cùng hàng triệu quân đội Sài Gòn) nhưng vẫn thất bại. Bài học lớn nhất: \"Không có gì quý hơn độc lập tự do\" (Hồ Chí Minh). Nghệ thuật chiến tranh nhân dân, kết hợp đấu tranh quân sự, chính trị và ngoại giao đã tạo nên sức mạnh tổng hợp vô địch.",
    "full_wiki": "Giai đoạn 1954–1960 – Đấu tranh chống Mỹ – Diệm:\n• Mỹ ký \"Hiệp ước phòng thủ chung\" với chính quyền Ngô Đình Diệm. Diệm phá hoại tổng tuyển cử, tổ chức \"tố Cộng diệt Cộng\".\n• 20/12/1960: Mặt trận Dân tộc giải phóng miền Nam Việt Nam ra đời.\n\nGiai đoạn 1961–1965 – Chiến tranh đặc biệt:\n• Mỹ thực hiện chiến lược \"Chiến tranh đặc biệt\": dùng quân đội Sài Gòn kết hợp cố vấn Mỹ chống lại ta.\n• 1/11/1963: Mỹ đứng sau đảo chính lật đổ Ngô Đình Diệm.\n\nGiai đoạn 1965–1968 – Chiến tranh cục bộ:\n• Mỹ ào ạt đưa quân chiến đấu vào miền Nam (đến 1969: hơn 500.000 quân).\n• Ta phá chiến lược \"Chiến tranh cục bộ\" bằng các chiến dịch lớn.\n• Tổng tiến công và nổi dậy Mậu Thân (tháng 1–2/1968): Tấn công đồng loạt vào 44 thành phố, thị xã, làm lung lay ý chí xâm lược của Mỹ, buộc Mỹ phải ngồi vào bàn đàm phán Paris.\n\nGiai đoạn 1969–1973 – Việt Nam hóa chiến tranh:\n• Nixon thực hiện \"Việt Nam hóa chiến tranh\": Rút dần quân Mỹ, dùng người Việt đánh người Việt.\n• Chiến dịch đường 9 – Nam Lào (1971): Đánh bại chiến lược này.\n• 27/1/1973: Hiệp định Paris về chấm dứt chiến tranh ở Việt Nam được ký kết. Mỹ cam kết rút hết quân.\n\nGiai đoạn 1973–1975 – Giải phóng hoàn toàn:\n• 10/3/1975: Chiến dịch Tây Nguyên. Ta giải phóng Buôn Ma Thuột.\n• Tháng 3/1975: Giải phóng toàn bộ miền Trung.\n• 26/4–30/4/1975: Chiến dịch Hồ Chí Minh. 5 cánh quân đồng loạt tiến công Sài Gòn.\n• 30/4/1975: Toàn thắng. Giang san thu về một mối.\n\nÝ nghĩa lịch sử:\n• Chấm dứt 30 năm chiến tranh (1945–1975).\n• Hoàn thành cách mạng dân tộc dân chủ nhân dân trong cả nước.\n• Mở ra kỷ nguyên hòa bình, thống nhất, cùng tiến lên xây dựng chủ nghĩa xã hội.\n• Để lại cho nhân loại bài học: Ý chí và sức mạnh đại đoàn kết dân tộc có thể chiến thắng mọi kẻ thù xâm lược.",
    "wikiLinks": {}
  },
  {
    "id": 12,
    "period": "Năm 1986",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "vietnam",
    "title": "Đại hội Đảng VI (12/1986) – Bước ngoặt Đổi mới toàn diện đất nước",
    "basic": "Đại hội đại biểu toàn quốc lần thứ VI của Đảng (12/1986) đề ra đường lối Đổi mới toàn diện đất nước. Trọng tâm là đổi mới kinh tế: chuyển từ cơ chế kế hoạch hóa tập trung, quan liêu, bao cấp sang nền kinh tế hàng hóa nhiều thành phần, vận hành theo cơ chế thị trường có sự quản lý của Nhà nước. Phương châm: \"Nhìn thẳng vào sự thật, đánh giá đúng sự thật, nói rõ sự thật\".",
    "advanced": "Đổi mới là quyết định dũng cảm và sáng suốt của Đảng, xuất phát từ nhận thức khách quan về thực trạng đất nước và xu thế phát triển của thế giới. Sau Đổi mới, Việt Nam thoát khỏi khủng hoảng kinh tế – xã hội trầm trọng, đạt tốc độ tăng trưởng GDP bình quân 7–8%/năm trong nhiều thập kỷ, từ một trong những nước nghèo nhất thế giới trở thành quốc gia có thu nhập trung bình thấp, hội nhập sâu rộng vào nền kinh tế thế giới.",
    "full_wiki": "Bối cảnh trước Đổi mới:\n• Sau thống nhất (1975), Việt Nam thống nhất trong điều kiện đất nước tàn phá nặng nề sau 30 năm chiến tranh.\n• Cơ chế kế hoạch hóa tập trung bộc lộ nhiều yếu kém: thiếu hàng hóa, lạm phát phi mã (trên 700%/năm), đời sống nhân dân rất khó khăn.\n• Hậu quả của Chiến tranh biên giới Tây Nam (1978–1979) và biên giới phía Bắc (1979) cộng thêm với cấm vận kinh tế của Mỹ.\n• Đại hội V (1982): Đảng nhận ra một số sai lầm, bắt đầu điều chỉnh. Khoán 100 (1981) cho phép giao khoán sản phẩm đến nhóm và hộ gia đình trong nông nghiệp.\n\nNội dung Đổi mới (Đại hội VI, 12/1986):\n1. Đổi mới tư duy:\n• Nhận thức lại về chủ nghĩa xã hội và con đường đi lên chủ nghĩa xã hội phù hợp với điều kiện Việt Nam.\n• Tôn trọng quy luật khách quan, chống chủ quan duy ý chí.\n\n2. Đổi mới kinh tế:\n• Xóa bỏ cơ chế tập trung bao cấp, chuyển sang cơ chế thị trường.\n• Phát triển kinh tế nhiều thành phần (nhà nước, tập thể, tư nhân, có vốn đầu tư nước ngoài).\n• Khoán 10 (1988): Giao quyền sử dụng đất lâu dài cho hộ nông dân, giải phóng lực lượng sản xuất nông thôn → Việt Nam từ nước thiếu lương thực trở thành nước xuất khẩu gạo top 3 thế giới.\n• Luật Đầu tư nước ngoài (1987): Mở cửa thu hút FDI.\n\n3. Đổi mới hệ thống chính trị:\n• Dân chủ hóa đời sống xã hội, tăng cường pháp chế.\n• Đổi mới phương thức lãnh đạo của Đảng và cải cách bộ máy nhà nước.\n\n4. Đổi mới đối ngoại:\n• Đa dạng hóa, đa phương hóa quan hệ quốc tế.\n• 1995: Bình thường hóa quan hệ với Mỹ, gia nhập ASEAN.\n• 2007: Gia nhập Tổ chức Thương mại Thế giới (WTO).\n\nKết quả nổi bật:\n• Thoát khỏi khủng hoảng kinh tế – xã hội trầm trọng.\n• GDP tăng trưởng mạnh, đời sống nhân dân cải thiện rõ rệt, tỷ lệ nghèo giảm từ trên 70% xuống còn dưới 10%.\n• Vị thế Việt Nam trên trường quốc tế được nâng cao đáng kể.",
    "wikiLinks": {}
  },
  {
    "id": 13,
    "period": "Năm 1917",
    "source": "SGK Lịch sử 11 – Biên soạn chuẩn",
    "category": "world",
    "title": "Cách mạng tháng Mười Nga – Nhà nước Xã hội chủ nghĩa đầu tiên ra đời",
    "basic": "Ngày 7/11/1917 (theo lịch Julien cũ là 25/10), cuộc Cách mạng tháng Mười Nga thắng lợi. Giai cấp vô sản Nga do Đảng Bônsêvích và V.I. Lenin lãnh đạo lật đổ Chính phủ tư sản lâm thời, thiết lập chính quyền Xô viết – nhà nước Xã hội chủ nghĩa đầu tiên trên thế giới.",
    "advanced": "Cách mạng tháng Mười Nga là sự kiện \"rung chuyển thế giới\". Lần đầu tiên trong lịch sử nhân loại, giai cấp công nhân và nhân dân lao động giành được chính quyền và xây dựng nhà nước của mình. Cách mạng mở ra một kỷ nguyên mới: Con người bước vào thời đại quá độ từ chủ nghĩa tư bản lên chủ nghĩa xã hội. Với lãnh tụ Nguyễn Ái Quốc, Cách mạng tháng Mười đã chỉ ra con đường giải phóng dân tộc Việt Nam.",
    "full_wiki": "Bối cảnh nước Nga trước Cách mạng:\n• Nước Nga tham gia Chiến tranh thế giới thứ nhất (1914) → thất bại nặng nề, kinh tế kiệt quệ, hàng triệu binh sĩ tử trận.\n• Chế độ quân chủ chuyên chế của Nga hoàng Nicolas II: bảo thủ, cai trị hà khắc, đời sống nhân dân cực khổ.\n\nCách mạng tháng Hai (3/1917):\n• Phong trào đình công và biểu tình của công nhân và binh lính nổ ra tại Petrograd.\n• Nga hoàng Nicolas II thoái vị. Chế độ quân chủ Romanov chấm dứt.\n• Tình trạng hai chính quyền song song: Chính phủ lâm thời tư sản và các Xô viết công – nông – binh.\n• Mâu thuẫn: Chính phủ lâm thời tiếp tục chiến tranh → nhân dân phẫn nộ.\n\nCách mạng tháng Mười (11/1917):\n• 4/1917: Lenin trở về Nga, đưa ra \"Luận cương tháng Tư\" chỉ ra nhiệm vụ chuyển từ cách mạng tư sản sang cách mạng xã hội chủ nghĩa.\n• 6/11/1917: Đảng Bônsêvích tổ chức khởi nghĩa vũ trang.\n• 7/11/1917 (25/10 theo lịch cũ): Chiếm Cung điện Mùa Đông. Chính phủ lâm thời sụp đổ. Chính quyền Xô viết ra đời.\n\nÝ nghĩa lịch sử:\n• Đối với nước Nga: Đưa nhân dân Nga thoát khỏi chiến tranh đế quốc. Mở ra kỷ nguyên xây dựng nhà nước xã hội chủ nghĩa đầu tiên.\n• Đối với thế giới: Là sự kiện trọng đại nhất của thế kỷ XX, phá vỡ mắt xích yếu nhất trong sợi dây chủ nghĩa đế quốc. Cổ vũ mạnh mẽ phong trào cách mạng vô sản và phong trào giải phóng dân tộc.\n• Đối với Việt Nam: 12/1920, Nguyễn Ái Quốc đọc Sơ thảo luận cương của Lenin → Nhận ra con đường giải phóng dân tộc đúng đắn duy nhất là đi theo Cách mạng tháng Mười.",
    "wikiLinks": {}
  },
  {
    "id": 14,
    "period": "Năm 1939 – Năm 1945",
    "source": "SGK Lịch sử 11 – Biên soạn chuẩn",
    "category": "world",
    "title": "Chiến tranh thế giới thứ hai (1939–1945) – Thảm họa và bài học lịch sử",
    "basic": "Ngày 1/9/1939, phát xít Đức tấn công Ba Lan, chính thức mở màn Chiến tranh thế giới thứ hai. Anh và Pháp tuyên chiến với Đức. Chiến tranh ngày càng lan rộng, thu hút tất cả các cường quốc: Mỹ (từ 12/1941), Liên Xô (từ 6/1941), Nhật Bản đứng về phe phát xít. Kết thúc bằng sự đầu hàng của Đức (5/5/1945) và Nhật (2/9/1945).",
    "advanced": "Chiến tranh thế giới thứ hai gây ra thảm họa khủng khiếp cho nhân loại: khoảng 70 triệu người thiệt mạng, trong đó 2/3 là thường dân; hàng chục thành phố lớn bị san bằng; tội ác diệt chủng Holocaust (tiêu diệt 6 triệu người Do Thái) là vết nhơ không thể xóa bỏ. Sau chiến tranh, Liên Hợp Quốc được thành lập (24/10/1945) nhằm duy trì hòa bình và an ninh quốc tế.",
    "full_wiki": "Nguyên nhân:\n• Mâu thuẫn giữa các cường quốc tư bản về thị trường, nguyên liệu và thuộc địa.\n• Hòa ước Versailles (1919) áp đặt các điều khoản khắc nghiệt lên Đức → Chủ nghĩa phục thù và phát xít trỗi dậy.\n• Chính sách \"dung túng\" của Anh, Pháp: Nhượng bộ Đức để hướng mũi nhọn phát xít về phía Liên Xô (Hiệp ước Munich 1938 trao Tiệp Khắc cho Đức).\n• Chủ nghĩa phát xít (Đức, Ý, Nhật) hiếu chiến, bành trướng.\n\nDiễn biến chủ yếu:\n• 1/9/1939: Đức tấn công Ba Lan. Chiến tranh bùng nổ.\n• 4–5/1940: Đức chiếm Bỉ, Hà Lan, Luxemburg, bắc nước Pháp. Quân Anh rút lui ở Dunkirk.\n• 22/6/1940: Pháp đầu hàng Đức.\n• 22/6/1941: Đức tấn công Liên Xô (Chiến dịch Barbarossa). Liên Xô gia nhập Đồng minh.\n• 7/12/1941: Nhật tấn công bất ngờ vào Trân Châu Cảng → Mỹ tuyên chiến với Nhật, gia nhập Chiến tranh.\n• 2/2/1943: Trận Stalingrad kết thúc (Đức đầu hàng tại Stalingrad) – Bước ngoặt của chiến tranh ở châu Âu.\n• 6/6/1944: Mặt trận thứ hai mở ở Tây Âu (Đồng minh đổ bộ Normandy, Pháp).\n• 8/5/1945: Đức đầu hàng vô điều kiện.\n• 6/8 và 9/8/1945: Mỹ ném hai quả bom nguyên tử xuống Hiroshima và Nagasaki.\n• 2/9/1945: Nhật đầu hàng – Chiến tranh thế giới thứ hai kết thúc.\n\nKết quả và hậu quả:\n• Khoảng 70 triệu người chết, hàng trăm triệu người bị thương và mất nhà cửa.\n• Kinh tế thế giới bị tàn phá nghiêm trọng. Nhiều thành phố lớn bị phá hủy hoàn toàn.\n• Liên Hợp Quốc được thành lập (24/10/1945) – tổ chức quốc tế lớn nhất nhằm duy trì hòa bình, an ninh.\n• Trật tự thế giới hai cực Yalta hình thành: Mỹ và Liên Xô trở thành hai siêu cường thống trị thế giới.\n• Phong trào giải phóng dân tộc được cổ vũ mạnh mẽ sau sự suy yếu của các đế quốc thực dân (Pháp, Anh, Hà Lan).",
    "wikiLinks": {}
  },
  {
    "id": 15,
    "period": "Năm 1945 – Năm 1991",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "world",
    "title": "Chiến tranh lạnh – Cuộc đối đầu Đông – Tây giữa hai siêu cường",
    "basic": "Chiến tranh lạnh (1947–1991) là cuộc đối đầu toàn diện về chính trị, kinh tế, quân sự và ý thức hệ giữa Mỹ (đứng đầu khối tư bản chủ nghĩa) và Liên Xô (đứng đầu hệ thống xã hội chủ nghĩa). Mặc dù không có chiến tranh trực tiếp giữa hai siêu cường, nhưng nhiều cuộc chiến tranh ủy nhiệm đã nổ ra: Triều Tiên (1950–1953), Việt Nam (1954–1975), Afghanistan (1979–1989)...",
    "advanced": "Chiến tranh lạnh định hình toàn bộ trật tự thế giới trong gần nửa thế kỷ. Cuộc chạy đua vũ trang hạt nhân giữa hai siêu cường đẩy nhân loại đến bờ vực tự hủy diệt, đỉnh điểm là Khủng hoảng tên lửa Cuba (10/1962). Kết thúc Chiến tranh lạnh (1991) với sự tan rã của Liên Xô đã thay đổi hoàn toàn bản đồ địa chính trị toàn cầu, mở ra kỷ nguyên toàn cầu hóa và hợp tác đa phương.",
    "full_wiki": "Nguồn gốc Chiến tranh lạnh:\n• Sau Chiến tranh thế giới thứ hai, Mỹ và Liên Xô là hai siêu cường duy nhất, có lợi ích và ý thức hệ đối lập.\n• 1947: Học thuyết Truman – Mỹ cam kết viện trợ cho các nước chống Cộng (trọng tâm là Hy Lạp và Thổ Nhĩ Kỳ).\n• 1947: Kế hoạch Marshall – Mỹ viện trợ kinh tế khổng lồ cho Tây Âu nhằm ngăn chặn ảnh hưởng của Liên Xô.\n• Liên Xô đáp lại: Thành lập Cominform (1947) và Comecon (1949).\n\nCác mốc quan trọng:\n• 1949: Bom nguyên tử Liên Xô thành công → Hai bên ngang bằng nhau về vũ khí hạt nhân.\n• 1949: NATO thành lập – Liên minh quân sự phương Tây. 1955: Khối Warszawa – Liên minh quân sự phía Đông.\n• 1950–1953: Chiến tranh Triều Tiên – Cuộc đối đầu gián tiếp đầu tiên giữa hai khối.\n• 1961: Bức tường Berlin xây dựng, chia đôi nước Đức và châu Âu.\n• 10/1962: Khủng hoảng tên lửa Cuba – Mỹ và Liên Xô đối đầu trực tiếp, nguy cơ chiến tranh hạt nhân rất gần. Sau 13 ngày căng thẳng, hai bên thỏa hiệp.\n• 1969–1979: Détente (Hòa dịu) – Mỹ và Liên Xô ký nhiều hiệp ước kiểm soát vũ khí.\n• 1979–1989: Liên Xô xâm lược Afghanistan → Chiến tranh lạnh trở nên căng thẳng.\n• 1985: Gorbachev lên cầm quyền, thực hiện \"Glasnost\" (Công khai) và \"Perestroika\" (Cải tổ).\n• 11/1989: Bức tường Berlin sụp đổ – biểu tượng kết thúc Chiến tranh lạnh.\n• 12/1991: Liên bang Xô viết tan rã – Chiến tranh lạnh kết thúc.\n\nHệ quả:\n• Thế giới từ đơn cực (Mỹ dẫn đầu) dần tiến đến đa cực phức tạp.\n• Xu thế hòa bình, hợp tác và toàn cầu hóa trở thành xu thế chủ đạo.\n• Nhiều điểm nóng vẫn tồn tại: Trung Đông, bán đảo Triều Tiên, xung đột sắc tộc...",
    "wikiLinks": {}
  },
  {
    "id": 16,
    "period": "Năm 1945 – Năm 1975",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "world",
    "title": "Phong trào giải phóng dân tộc ở châu Á, châu Phi và Mỹ Latinh",
    "basic": "Sau Chiến tranh thế giới thứ hai, làn sóng giải phóng dân tộc bùng nổ mạnh mẽ khắp châu Á, châu Phi và Mỹ Latinh. Đến cuối những năm 1970, hệ thống thuộc địa của các đế quốc phương Tây về cơ bản tan rã. Năm 1960 được gọi là \"Năm châu Phi\" – có tới 17 quốc gia ở lục địa này cùng tuyên bố độc lập.",
    "advanced": "Phong trào giải phóng dân tộc là một trong những xu thế lớn nhất của thế kỷ XX. Chiến thắng Điện Biên Phủ (1954) của nhân dân Việt Nam có tác động mạnh mẽ, cổ vũ tinh thần các dân tộc bị áp bức trên thế giới, đặc biệt tại châu Phi. Sau khi giành được độc lập về chính trị, nhiều nước phải tiếp tục đấu tranh chống lại chủ nghĩa thực dân mới (neocolonialism) về kinh tế.",
    "full_wiki": "Châu Á:\n• 1945: Nhiều nước Đông Nam Á tuyên bố độc lập: Việt Nam (2/9/1945), Indonesia (17/8/1945).\n• 1947: Ấn Độ và Pakistan giành độc lập từ Anh. Mahatma Gandhi lãnh đạo phong trào bất bạo động.\n• 1949: Nước Cộng hòa Nhân dân Trung Hoa ra đời (1/10/1949) dưới sự lãnh đạo của Mao Trạch Đông.\n• 1954: Hiệp định Giơnevơ công nhận độc lập của Việt Nam, Lào, Campuchia.\n• 1960: Phong trào Phi liên kết (NAM) thành lập tại Hội nghị Bandung (1955) → các nước mới độc lập không liên kết với cả hai phe.\n\nChâu Phi:\n• 1952: Cách mạng Ai Cập lật đổ vua Farouk. Gamal Abdel Nasser lên cầm quyền.\n• 1956: Nasser quốc hữu hóa kênh đào Suez → Anh, Pháp, Israel tấn công nhưng phải rút lui do áp lực của Mỹ và Liên Xô.\n• 1957: Ghana là quốc gia châu Phi đầu tiên giành độc lập từ thực dân Anh dưới sự lãnh đạo của Kwame Nkrumah.\n• 1960: \"Năm châu Phi\" – 17 quốc gia tuyên bố độc lập. Liên Hợp Quốc thông qua \"Tuyên bố về trao trả độc lập cho các dân tộc và các quốc gia thuộc địa\".\n• 1962: Angiêri giành độc lập sau 8 năm chiến tranh chống Pháp.\n• 1975: Angola và Mozambique độc lập, chấm dứt hệ thống thực dân Bồ Đào Nha.\n• 1990: Namibia độc lập – quốc gia thuộc địa cuối cùng ở châu Phi.\n• 1994: Nelson Mandela được bầu làm Tổng thống Nam Phi – xóa bỏ chế độ phân biệt chủng tộc Apartheid.\n\nMỹ Latinh:\n• 1959: Cách mạng Cuba thắng lợi. Fidel Castro lên cầm quyền.\n• Phong trào đấu tranh chống can thiệp của Mỹ ở nhiều nước (Nicaragua, El Salvador, Chile...).\n\nĐặc điểm chung:\n• Hình thức đấu tranh đa dạng: Vũ trang cách mạng, đấu tranh chính trị ôn hòa, ngoại giao.\n• Vai trò của tổ chức quốc tế: OAU (Tổ chức Thống nhất châu Phi, 1963), NAM.\n• Thách thức sau độc lập: Chủ nghĩa thực dân mới, đói nghèo, xung đột nội bộ.",
    "wikiLinks": {}
  },
  {
    "id": 17,
    "period": "Năm 1950 – Năm 1973",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "world",
    "title": "Sự phát triển \"thần kỳ\" của Nhật Bản sau Chiến tranh thế giới thứ hai",
    "basic": "Sau thất bại trong Chiến tranh thế giới thứ hai (1945), Nhật Bản bị tàn phá nặng nề và bị Mỹ chiếm đóng. Nhưng từ những năm 1950, kinh tế Nhật Bản phục hồi nhanh chóng và bước vào giai đoạn phát triển \"thần kỳ\": tốc độ tăng trưởng GDP bình quân 10%/năm trong suốt hai thập kỷ. Đến năm 1968, Nhật Bản trở thành nền kinh tế lớn thứ hai thế giới (sau Mỹ).",
    "advanced": "Sự phát triển thần kỳ của Nhật Bản được giải thích bởi nhiều yếu tố: Con người (giáo dục chất lượng cao, tinh thần kỷ luật và làm việc chăm chỉ); Nhà nước điều phối kinh tế hiệu quả (MITI – Bộ Công nghiệp và Thương mại quốc tế); Chi phí quốc phòng thấp (Hiến pháp 1947 cấm quân đội tấn công); Tiếp thu và đổi mới công nghệ nhanh chóng. Đây là mô hình phát triển kinh tế được nhiều nước châu Á học hỏi.",
    "full_wiki": "Nhật Bản sau Chiến tranh thế giới thứ hai (1945):\n• Đất nước bị tàn phá hoàn toàn: 2 thành phố bị bom nguyên tử, hàng chục thành phố lớn bị ném bom, 3 triệu người chết.\n• Mỹ chiếm đóng (1945–1952): Cải cách dân chủ: Hiến pháp 1947 (Điều 9 cấm chiến tranh), tan rã zaibatsu (tập đoàn tư bản lũng đoạn), cải cách ruộng đất, mở rộng quyền bầu cử cho phụ nữ.\n\nCác nhân tố \"thần kỳ kinh tế\":\n1. Con người:\n• Dân số có trình độ giáo dục cao, tỷ lệ mù chữ gần bằng 0.\n• Tinh thần lao động cần cù, kỷ luật, trung thành với công ty.\n• Hệ thống \"việc làm suốt đời\" và \"thâm niên\": Nhân viên tận tâm cống hiến cho công ty.\n\n2. Vai trò của nhà nước:\n• MITI định hướng phát triển công nghiệp, bảo hộ ngành công nghiệp non trẻ.\n• Đầu tư mạnh vào giáo dục, nghiên cứu và phát triển (R&D).\n\n3. Chi phí quốc phòng thấp:\n• Hiến pháp 1947 (Điều 9) cấm Nhật có quân đội tấn công → tiết kiệm ngân sách cho phát triển kinh tế.\n• Mỹ đảm bảo an ninh cho Nhật.\n\n4. Tiếp thu công nghệ:\n• Mua bằng sáng chế, công nghệ từ phương Tây với giá rẻ rồi cải tiến, sáng tạo thêm.\n• Tập trung vào xuất khẩu hàng chất lượng cao: ô tô, điện tử, thép.\n\nKết quả:\n• 1968: Nhật trở thành nền kinh tế lớn thứ 2 thế giới.\n• Tạo ra mô hình phát triển \"con rồng châu Á\" được Hàn Quốc, Singapore, Đài Loan học hỏi.",
    "wikiLinks": {}
  },
  {
    "id": 18,
    "period": "Năm 1967",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "world",
    "title": "ASEAN – Hành trình từ tổ chức khu vực đến Cộng đồng ASEAN",
    "basic": "Ngày 8/8/1967, Hiệp hội các Quốc gia Đông Nam Á (ASEAN) được thành lập tại Bangkok (Thái Lan) với 5 thành viên ban đầu: Thái Lan, Malaysia, Singapore, Indonesia và Philippines. Tuyên bố Bangkok (1967) xác định mục tiêu: Thúc đẩy hợp tác kinh tế, văn hóa, giáo dục và xã hội; duy trì hòa bình và ổn định khu vực.",
    "advanced": "ASEAN trải qua nhiều giai đoạn phát triển, từ tổ chức 5 thành viên năm 1967 đến cộng đồng 10 nước ngày nay (thêm Brunei 1984, Việt Nam 1995, Lào và Myanmar 1997, Campuchia 1999). Ngày 31/12/2015, Cộng đồng ASEAN chính thức ra đời với 3 trụ cột: Cộng đồng Chính trị – An ninh, Cộng đồng Kinh tế và Cộng đồng Văn hóa – Xã hội.",
    "full_wiki": "Hoàn cảnh ra đời:\n• Khu vực Đông Nam Á những năm 1960 đầy biến động: Chiến tranh Việt Nam leo thang, cách mạng tại Indonesia (1965), tranh chấp lãnh thổ giữa các nước trong khu vực.\n• Các nước sáng lập muốn có một tổ chức hợp tác khu vực để ổn định, phát triển và cùng nhau đối phó với nguy cơ Cộng sản.\n\nCác giai đoạn phát triển:\n• Giai đoạn 1967–1976 (hợp tác lỏng lẻo): Hoạt động chủ yếu mang tính biểu tượng. Năm 1971: Tuyên bố khu vực hòa bình, tự do và trung lập (ZOPFAN).\n• Giai đoạn 1976–1990 (củng cố): Hội nghị Thượng đỉnh Bali (1976) với Hiệp ước Thân thiện và Hợp tác (TAC) tạo nền tảng quan hệ giữa các thành viên.\n• Giai đoạn 1990–1999 (mở rộng): Việt Nam gia nhập (7/1995), Lào và Myanmar (1997), Campuchia (1999) → ASEAN 10.\n• Giai đoạn từ 2000 (Cộng đồng ASEAN): 31/12/2015 Cộng đồng ASEAN chính thức thành lập.\n\nViệt Nam và ASEAN:\n• 28/7/1995: Việt Nam chính thức trở thành thành viên thứ 7 của ASEAN.\n• Quan hệ Việt Nam – ASEAN chuyển từ đối đầu (giai đoạn chiếm đóng Campuchia, 1979–1989) sang hợp tác toàn diện.\n• Việt Nam ngày càng đóng vai trò tích cực và có trách nhiệm trong ASEAN.\n\nVai trò và ý nghĩa của ASEAN:\n• Tạo dựng môi trường hòa bình, ổn định cho phát triển kinh tế.\n• Cộng đồng 10 nước với khoảng 680 triệu dân, GDP tổng hợp đạt hơn 3 nghìn tỷ USD – một trong những khu vực kinh tế năng động nhất thế giới.",
    "wikiLinks": {}
  },
  {
    "id": 19,
    "period": "Năm 1991 – Năm 2000",
    "source": "SGK Lịch sử 12 – Biên soạn chuẩn",
    "category": "world",
    "title": "Trật tự thế giới sau Chiến tranh lạnh – Toàn cầu hóa và xu thế hòa bình",
    "basic": "Sau khi Chiến tranh lạnh kết thúc và Liên Xô tan rã (1991), thế giới chuyển sang trật tự mới: ban đầu là đơn cực với Mỹ là siêu cường duy nhất, sau đó dần tiến đến đa cực phức tạp. Xu thế hòa bình và hợp tác trở thành chủ đạo nhưng nhiều điểm nóng vẫn tồn tại. Toàn cầu hóa kinh tế và cách mạng khoa học – công nghệ tạo ra sự kết nối chưa từng có trong lịch sử.",
    "advanced": "Toàn cầu hóa là quá trình khách quan, vừa tạo ra cơ hội phát triển to lớn vừa đặt ra những thách thức gay gắt, đặc biệt cho các nước đang phát triển. Xu thế vừa hợp tác vừa cạnh tranh giữa các quốc gia ngày càng gay gắt. Các vấn đề toàn cầu nổi lên: biến đổi khí hậu, khủng bố quốc tế, dịch bệnh (COVID-19), bất bình đẳng giàu nghèo đòi hỏi phải hợp tác đa phương để giải quyết.",
    "full_wiki": "Trật tự thế giới sau 1991:\n\nĐặc điểm của thế giới đương đại:\n• Xu thế hòa bình và hợp tác: Sau Chiến tranh lạnh, nguy cơ chiến tranh thế giới giảm đi đáng kể.\n• Cạnh tranh kinh tế thay thế chạy đua vũ trang: Các cường quốc cạnh tranh nhau bằng kinh tế, công nghệ hơn là quân sự.\n• Đa cực hóa: Mỹ, Trung Quốc, Nga, EU, Nhật Bản... cùng định hình trật tự thế giới.\n• Vai trò của Trung Quốc: Trỗi dậy mạnh mẽ, trở thành nền kinh tế lớn thứ 2 thế giới từ năm 2010.\n\nToàn cầu hóa:\n• Internet và công nghệ thông tin kết nối thế giới – \"Thế giới phẳng\" (Thomas Friedman).\n• Thương mại và đầu tư quốc tế bùng nổ. WTO (thành lập 1/1/1995) quản lý thương mại toàn cầu.\n• Dòng chảy tự do của vốn, hàng hóa, công nghệ và thông tin xuyên biên giới.\n• Mặt trái: Sự phụ thuộc lẫn nhau làm gia tăng tính dễ tổn thương (khủng hoảng tài chính 1997, 2008 lan nhanh toàn cầu).\n\nCác vấn đề toàn cầu nổi lên:\n• Khủng bố quốc tế: 11/9/2001 – Mỹ phát động \"Cuộc chiến chống khủng bố toàn cầu\".\n• Biến đổi khí hậu: Hiệp định Paris về khí hậu (2015).\n• Dịch bệnh xuyên biên giới (COVID-19 từ 2019).\n• Bất bình đẳng giàu nghèo ngày càng gia tăng trong và giữa các quốc gia.\n\nXu thế khu vực hóa:\n• EU (Liên minh châu Âu, chính thức 1993): Thể hiện rõ nhất xu thế liên kết khu vực sâu sắc.\n• APEC, ASEAN+3, SCO... phát triển mạnh.\n• Việt Nam và các nước đang phát triển: Cơ hội lớn từ hội nhập quốc tế, nhưng đòi hỏi phải không ngừng cải cách để cạnh tranh hiệu quả.",
    "wikiLinks": {}
  },
  {
    "id": 20,
    "period": "NĂM ...",
    "category": "vietnam",
    "title": "Sự kiện mới chưa có tiêu đề",
    "basic": "",
    "advanced": "",
    "full_wiki": "",
    "wikiLinks": {}
  },
  {
    "id": 21,
    "period": "NĂM ...",
    "category": "world",
    "title": "Sự kiện mới chưa có tiêu đề",
    "basic": "",
    "advanced": "",
    "full_wiki": "",
    "wikiLinks": {}
  }
];
